import { NextResponse } from 'next/server';

export async function GET() {
    const sebagai = {
        PES: "Peserta Kegiatan",
        PAN: "Panitia Kegiatan",
    };

    const jenis = {
        LOM: "Lomba",
        SEM: "Seminar",
        PEL: "Pelatihan",
        ORG: "Organisasi",
    };

    const tingkat = {
        NAS: "Nasional",
        UNY: "Universitas Negeri Yogyakarta",
        REG: "Regional",
        INT: "Internasional",
    };

    const data = [
        {
            id: 1,
            name: "National Competition for Reasoning 'NALAR. IN' Year 2023",
            description: "Participated in a national reasoning competition organized by Yogyakarta State University to sharpen logical and analytical thinking skills.",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/1-1.png",
                "/images/kegiatan/1-2.png",
            ],
            startDate: "2023-03-13",
            endDate: "2023-03-13",
            tempat: "Universitas Negeri Yogyakarta",
            penyelenggara: "Universitas Negeri Yogyakarta",
            tingkat: "NAS",
        },
        {
            id: 2,
            name: "National Level Indonesian Performing Arts Festival (FSPI) 2023",
            description: "Participated in a national Indonesian performing arts festival showcasing various traditional and contemporary art and cultural works.",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/2-2.jpeg",
                "/images/kegiatan/2-1.jpg",
            ],
            startDate: "2023-03-01",
            endDate: "2023-04-28",
            tempat: "UNIVERSITAS NEGERI YOGYAKARTA",
            penyelenggara: "FSPI UNIVERSITAS NEGERI YOGYAKARTA",
            tingkat: "NAS",
        },
        {
            id: 3,
            name: "Community Service",
            description: "Participated in community service activities in Batanggede Village to provide real contributions to the community through various social and empowerment programs.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/3-2.jpeg",
                "/images/kegiatan/3-1.jpg",
            ],
            startDate: "2023-09-16",
            endDate: "2023-09-17",
            tempat: "Dusun Batanggede, Kelurahan Tambak Rejo, Tempel, Sleman, Yogyakarta",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 4,
            name: "Humanitarian Project",
            description: "Participated in a humanitarian program by visiting an orphanage to share happiness and provide assistance to children in need.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/4-2.jpeg",
                "/images/kegiatan/4-1.png",
            ],
            startDate: "2023-09-02",
            endDate: "2023-09-02",
            tempat: "Panti Asuhan Al - Hikmah Sejalan, Wukirsari, Cangkringan, Plosokarep, Umbulharjo, Selman, DI Yogyakarta",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 5,
            name: "Industrial Visit",
            description: "Participated in an industrial visit to Jakarta and Bandung to learn firsthand about the application of knowledge in the workplace and expand industry insights.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/5-2.jpeg",
                "/images/kegiatan/5-1.png",
            ],
            startDate: "2023-09-04",
            endDate: "2023-09-07",
            tempat: "Jakarta - Bandung",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 6,
            name: "ARTOCIUS Poster & Short Movie NATIONAL COMPETITION 2023",
            description: "Participated in a national poster and short film competition with creative themes organized online.",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/6-2.jpeg",
                "/images/kegiatan/6-1.jpg",
            ],
            startDate: "2023-07-22",
            endDate: "2023-07-31",
            tempat: "online",
            penyelenggara: "Himpunan Mahasiswa Pendidikan IPS Bidang Media dan Jaringan",
            tingkat: "NAS",
        },
        {
            id: 7,
            name: "National Seminar on Electronics and Information Engineering Education (SNPTEI) 2023",
            description: "Attended a national seminar on electronics and informatics engineering education to gain current insights from experts and practitioners.",
            sebagai: "PAN",
            jenis: "SEM",
            images: [
                "/images/kegiatan/7-2.jpeg",
                "/images/kegiatan/7-1.png",
            ],
            startDate: "2023-09-26",
            endDate: "2023-09-26",
            tempat: "Fakultas Teknik UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 8,
            name: "Seminar Nasional Matematika Ke-15 Universitas Gadjah Mada 'The Future of Criptography and Cybersecurity in Industrial Application'",
            description: "Attended a seminar on the future of cryptography and cybersecurity in industrial applications organized by Gadjah Mada University.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/8-2.jpeg",
                "/images/kegiatan/8-1.jpeg",
                "/images/kegiatan/8-3.png",
            ],
            startDate: "2023-09-24",
            endDate: "2023-09-24",
            tempat: "FMIPA UGM",
            penyelenggara: "Himatika UGM",
            tingkat: "NAS",
        },
        {
            id: 9,
            name: "National Seminar with the theme 'Economic Literacy and Business in the 5.0 Era'",
            description: "Attended a national seminar on economic literacy and business in the 5.0 era to understand current digital economic developments.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/9-2.jpeg",
                "/images/kegiatan/9-1.jpeg",
                "/images/kegiatan/9-3.png",
            ],
            startDate: "2023-05-27",
            endDate: "2023-05-27",
            tempat: "FEB UNY",
            penyelenggara: "HMPE FEB UNY",
            tingkat: "NAS",
        },
        {
            id: 10,
            name: "Digital Economy Academy",
            description: "Participated in a learning program on digital economy and digital transformation across various industry sectors.",
            sebagai: "PES",
            jenis: "PEL",
            images: [
                "/images/kegiatan/10-2.jpeg",
                "/images/kegiatan/10-1.jpeg",
                "/images/kegiatan/10-3.png",
            ],
            startDate: "2023-06-24",
            endDate: "2023-06-24",
            tempat: "Ruang Ki Hadjar Dewantara, Fakultas Ilmu Sosial, Hukum dan Ilmu Politik Universitas Negeri Yogyakarta",
            penyelenggara: "BEM KM UNY",
            tingkat: "NAS",
        },
        {
            id: 11,
            name: "Seminar Brave Public Speaking 'Unlock Your Voice, Take Your Chance'",
            description: "Attended a public speaking seminar to improve public speaking and effective communication skills.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/11-2.jpeg",
                "/images/kegiatan/11-1.jpeg",
                "/images/kegiatan/11-3.png",
            ],
            startDate: "2024-04-27",
            endDate: "2024-04-27",
            tempat: "Aula Lantai 3 Gedung Student Center UNY",
            penyelenggara: "FOMUNY 2024",
            tingkat: "UNY",
        },
        {
            id: 12,
            name: "Seminar Brave Public Speaking with Fomuny 'Be A Good Speaker for The Better Future''",
            description: "Attended a seminar on becoming a good speaker for a better future with practical public speaking techniques.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/12-2.jpeg",
                "/images/kegiatan/12-1.jpeg",
                "/images/kegiatan/12-3.png",
            ],
            startDate: "2023-03-04",
            endDate: "2023-03-04",
            tempat: "Zoom Meeting / Aula Lantai 3 Gedung Student Center UNY",
            penyelenggara: "FOMUNY 2023",
            tingkat: "UNY",
        },
        {
            id: 13,
            name: "Smart Way For TOEFL FOMUNY 2023 'Do your best and reach your achievement with TOEFL'",
            description: "Attended a seminar on smart strategies for facing TOEFL tests to improve English language skills and test preparation.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/13-1.jpeg",
                "/images/kegiatan/13-2.png",
            ],
            startDate: "2023-09-02",
            endDate: "2023-09-02",
            tempat: "Zoom Meeting / Gedung KPLT Lantai 2 FT UNY",
            penyelenggara: "FOMUNY 2023",
            tingkat: "UNY",
        },
        {
            id: 14,
            name: "Media School 'Become a Logo Design Expert in the industrial Field of the Modern Era'",
            description: "Participated in professional logo design training in the context of modern industry to develop graphic design skills.",
            sebagai: "PES",
            jenis: "PEL",
            images: [
                "/images/kegiatan/14-2.jpeg",
                "/images/kegiatan/14-1.jpeg",
                "/images/kegiatan/14-3.png",
            ],
            startDate: "2024-05-19",
            endDate: "2024-05-19",
            tempat: "FISHIPOL UNY",
            penyelenggara: "HIMA PKnH 2024",
            tingkat: "UNY",
        },
        {
            id: 15,
            name: "Campus Orientation DPTEI UNY 2023",
            description: "Participated as committee member in campus orientation activities for new DPTEI students to assist in the adaptation process of new students.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/15-2.jpeg",
                "/images/kegiatan/15-1.png",
            ],
            startDate: "2023-08-11",
            endDate: "2023-08-11",
            tempat: "DPTEI FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 16,
            name: "SHIBERNIKA Leadership Training 2023",
            description: "Participated in HIMANIKA leadership training to develop soft skills and organizational capabilities at Tinalah Tourism Village.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/16-2.jpeg",
                "/images/kegiatan/16-1.png",
            ],
            startDate: "2023-09-30",
            endDate: "2023-10-01",
            tempat: "Desa Wisata Tinalah",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 17,
            name: "PI and Student Internship Debriefing Information",
            description: "Attended debriefing information on industrial practice and student internships as preparation for entering the professional world.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/17-2.jpeg",
                "/images/kegiatan/17-1.jpeg",
                "/images/kegiatan/17-3.png",
            ],
            startDate: "2024-03-27",
            endDate: "2024-03-28",
            tempat: "Aula KPLT Lt.3 FT UNY",
            penyelenggara: "FT UNY",
            tingkat: "UNY",
        },
        {
            id: 18,
            name: "Upgrading HIMANIKA Management 2023",
            description: "Participated in HIMANIKA management upgrading activities to enhance organizational capacity and team cohesiveness.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/18-2.jpeg",
                "/images/kegiatan/18-1.png",
            ],
            startDate: "2023-05-20",
            endDate: "2023-05-21",
            tempat: "Villa Pondok Omah Kayu",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 19,
            name: "HIMANIKA Humanitarian Project 2024",
            description: "Participated in HIMANIKA humanitarian program to help communities in need in the Bantul region.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/19-2.jpeg",
                "/images/kegiatan/19-1.png",
            ],
            startDate: "2024-05-05",
            endDate: "2024-05-05",
            tempat: "Jl. Pajangan, KalakIjo, Guwosari, Kec. Pajangan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55751",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 20,
            name: "HIMANIKA Community Service 2024",
            description: "Participated in HIMANIKA community service activities providing real contributions to the community in Guwosari, Pajangan.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/20-2.jpeg",
                "/images/kegiatan/20-1.png",
            ],
            startDate: "2024-05-04",
            endDate: "2024-05-05",
            tempat: "Jl. Pajangan, KalakIjo, Guwosari, Kec. Pajangan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55751",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 21,
            name: "UPGRADING HIMANIKA 2024",
            description: "Attended HIMANIKA upgrading activities for organizational strengthening and improvement of management quality in Wijirejo, Pandak.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/21-2.jpeg",
                "/images/kegiatan/21-1.png",
            ],
            startDate: "2024-05-11",
            endDate: "2024-05-12",
            tempat: "Jl. Sedayu-Gesikan, Gesikan I, Wijirejo, Kec. Pandak, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55761",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 22,
            name: "Comparative Study of KMTEDI SV UGM X HIMANIKA FT UNY",
            description: "Participated in a comparative study with KMTEDI SV UGM to share organizational experiences and build inter-campus networking.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/22-2.jpeg",
                "/images/kegiatan/22-1.png",
                "/images/kegiatan/22-3.png",
            ],
            startDate: "2023-09-24",
            endDate: "2023-09-24",
            tempat: "Hall Perpustakaan SV UGM",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 23,
            name: "HME FT UNY X HIMANIKA FT UNY Visit Reception",
            description: "Received a visit from HME FT UNY to establish friendship and cooperation between student associations.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/23-2.jpeg",
                "/images/kegiatan/23-1.png",
                "/images/kegiatan/23-3.png",
            ],
            startDate: "2023-06-17",
            endDate: "2023-06-17",
            tempat: "Ruang Teater FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 24,
            name: "Comparative Study of HIMANIKA FT UNY X HIMAKI UNY",
            description: "Conducted a comparative study with HIMAKI UNY to share best practices and strengthen inter-organizational collaboration.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/24-2.jpeg",
                "/images/kegiatan/24-1.png",
                "/images/kegiatan/24-3.png",
            ],
            startDate: "2023-04-02",
            endDate: "2023-04-02",
            tempat: "Ruang Seminar FMIPA",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 25,
            name: "ENTREPRENEURSHIP DISCUSSION 'Mastering Content Marketing: Rahasia Sukses Tingkatkan Penjualan Lewat Konten Kreatif di 3 Platform Sekaligus (Reels, TikTok,&Short)'",
            description: "Participated in an entrepreneurship discussion on content marketing and strategies to increase sales through creative content on various social media platforms.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/25-2.jpeg",
                "/images/kegiatan/25-1.jpeg",
                "/images/kegiatan/25-3.png",
            ],
            startDate: "2023-09-17",
            endDate: "2023-09-17",
            tempat: "ABDULLAH SIGIT HALL LANTAI 3",
            penyelenggara: "BEM FIPP UNY",
            tingkat: "UNY",
        },
        {
            id: 26,
            name: "KOSAN#3 National Insight Towards the 2024 Elections",
            description: "Attended a national insight seminar discussing the political situation leading up to the 2024 elections and the role of young generation.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/26-2.jpeg",
                "/images/kegiatan/26-1.png",
                "/images/kegiatan/26-3.png",
            ],
            startDate: "2023-05-04",
            endDate: "2023-05-04",
            tempat: "Takom 1922 Cafe & Resto Yogyakarta",
            penyelenggara: "Garda Institute",
            tingkat: "NAS",
        },
        {
            id: 27,
            name: "Metaverse and IoT with Python Seminar and Workshop",
            description: "Participated in a seminar and workshop on metaverse and Internet of Things with Python to understand future technologies.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/27-1.png",
                "/images/kegiatan/27-3.png",
            ],
            startDate: "2023-11-05",
            endDate: "2023-11-05",
            tempat: "UGM",
            penyelenggara: "HMEI UGM",
            tingkat: "NAS",
        },
        {
            id: 28,
            name: "[Astra Career Meet Up] ACMU Yogyakarta Series 2023",
            description: "Attended a career meet up with PT Astra International to learn about career opportunities and tips for entering the industry world.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/28-2.jpeg",
                "/images/kegiatan/28-1.jpeg",
                "/images/kegiatan/28-3.png",
            ],
            startDate: "2023-10-28",
            endDate: "2023-10-28",
            tempat: "Grha Sabha Pramana UGM",
            penyelenggara: "PT Astra International Tbk.",
            tingkat: "NAS",
        },
        {
            id: 29,
            name: "Smart City Outlook National Seminar 2023: BIG DATA",
            description: "Participated in a national seminar on big data in the context of smart cities to understand data utilization in smart city development.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/29-2.jpeg",
                "/images/kegiatan/29-1.jpeg",
                "/images/kegiatan/29-3.png",
            ],
            startDate: "2023-10-14",
            endDate: "2023-10-14",
            tempat: "Fakultas Matematika dan Ilmu Pengetahuan Alam Universitas Gadjah Mada",
            penyelenggara: "Laboratorium Riset Sistem Komputer dan Jaringan",
            tingkat: "NAS",
        },
        {
            id: 30,
            name: "INFINITE x GDSC UNY Learning Path: Study Camp 2024 path Hacker",
            description: "Participated in a learning path study camp hacker track program to improve cybersecurity skills and ethical hacking.",
            sebagai: "PES",
            jenis: "PEL",
            images: [
                "/images/kegiatan/30-2.jpeg",
                "/images/kegiatan/30-1.png",
                "/images/kegiatan/30-3.png",
            ],
            startDate: "2024-02-25",
            endDate: "2024-03-24",
            tempat: "Ruang Teater FT UNY",
            penyelenggara: "INFINITE x GDSC UNY",
            tingkat: "UNY",
        },
        {
            id: 31,
            name: "TALK ABOUT THE BUREAUCRACY OF THE ELECTRONICS AND INFORMATICS STUDENT ASSOCIATION",
            description: "Participated in internal discussions about organizational governance and bureaucratic systems to enhance understanding of HIMANIKA's organizational structure.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/31-2.jpeg",
                "/images/kegiatan/31-1.jpeg",
                "/images/kegiatan/31-3.png",
            ],
            startDate: "2023-05-13",
            endDate: "2023-05-13",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 32,
            name: "ELINATION #5 (Electronics and Informatics Competition)",
            description: "Participated as committee member in a national-level electronics and informatics competition to develop organizational and technical skills.",
            sebagai: "PAN",
            jenis: "LOM",
            images: [
                "/images/kegiatan/32-2.jpeg",
                "/images/kegiatan/32-1.jpeg",
                "/images/kegiatan/32-3.png",
            ],
            startDate: "2023-10-21",
            endDate: "2023-10-21",
            tempat: "Gedung IDB FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 33,
            name: "HIMANIKAFEST 2023 Virtual Reality Festivity",
            description: "Participated in a technology festival themed around virtual reality showcasing various innovations and developments in immersive technology.",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/33-2.png",
                "/images/kegiatan/33-1.png",
                "/images/kegiatan/33-3.png",
            ],
            startDate: "2023-10-28",
            endDate: "2023-10-28",
            tempat: "Gedung Parkir Terpadu UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 34,
            name: "Webinar English Series: How to be Sucessful in Public Speaking",
            description: "Attended a webinar on public speaking techniques in English to improve presentation and international communication skills.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/34-2.png",
                "/images/kegiatan/34-1.jpeg",
                "/images/kegiatan/34-3.png",
            ],
            startDate: "2024-07-09",
            endDate: "2024-07-09",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "BELAJAR ERA DIGITAR",
            tingkat: "NAS",
        },
        {
            id: 35,
            name: "Edtech Webinar titled: 'Optimizing Classpoint in Teaching English Tenses'",
            description: "Attended a webinar on optimizing Classpoint educational technology in English language teaching to understand edtech innovations.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/35-2.png",
                "/images/kegiatan/35-1.jpeg",
                "/images/kegiatan/35-3.png",
            ],
            startDate: "2024-07-07",
            endDate: "2024-07-07",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "High Tech Teacher Indonesia",
            tingkat: "NAS",
        },
        {
            id: 36,
            name: "Webinar English Series: Acquire and Memorize English Vocabulary Effectively",
            description: "Attended a webinar on effective strategies for acquiring and memorizing English vocabulary to enhance language proficiency.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/36-2.png",
                "/images/kegiatan/36-1.jpeg",
                "/images/kegiatan/36-3.png",
            ],
            startDate: "2024-07-02",
            endDate: "2024-07-02",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "BELAJAR ERA DIGITAR",
            tingkat: "NAS",
        },
        {
            id: 37,
            name: "Data Series Fair 10.0 - Data Engineer",
            description: "Participated in a data engineering training program to learn techniques for processing, transforming, and managing large-scale data.",
            sebagai: "PES", 
            jenis: "PEL",
            images: [
                "/images/kegiatan/37-2.png",
                "/images/kegiatan/37-1.jpeg",
                "/images/kegiatan/37-3.png",
            ],
            startDate: "2024-07-15",
            endDate: "2024-07-22",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "Dibimbing",
            tingkat: "NAS",
        },
        {
            id: 38,
            name: "TECH TALK 2024 'The Use of AI in the Film Industry and the Consequences of Digital Products in the Future'",
            description: "Attended a technology discussion on AI applications in the film industry and the impact of digital products on the future of creative industries.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/38-2.png",
                "/images/kegiatan/38-1.jpeg",
            ],
            startDate: "2024-06-29",
            endDate: "2024-06-29",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "ukm restekuny",
            tingkat: "NAS",
        },
        {
            id: 39,
            name: "National Webinar by Authentic Publishing with the theme 'Challenges and Opportunities in Scientific Journal Publication'",
            description: "Participated in a national webinar on challenges and opportunities in scientific journal publication to understand research and academic publishing processes.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/39-2.jpeg",
                "/images/kegiatan/39-1.jpeg",
                "/images/kegiatan/39-3.png",
            ],
            startDate: "2024-07-17",
            endDate: "2024-07-17",
            tempat: "Online melalui Zoom Meeting",
            penyelenggara: "authenticpublishing",
            tingkat: "NAS",
        },
        {
            id: 40,
            name: "Comparative Study of HIMANIKA FT UNY with ITECH UNISA",
            description: "Conducted a comparative study with ITECH UNISA to share organizational experiences and build inter-university collaboration.",
            sebagai: "PAN", 
            jenis: "ORG",
            images: [
                "/images/kegiatan/40-2.png",
                "/images/kegiatan/40-1.jpeg",
            ],
            startDate: "2024-05-24",
            endDate: "2024-05-24",
            tempat: "Gedung KPLT FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 41,
            name: "UBMCC 2024 'Creativepreneurship in supporting Indonesia MSMEs'",
            description: "Participated in a competition on creative entrepreneurship supporting Indonesian MSMEs to develop innovative business ideas.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/41-2.png",
                "/images/kegiatan/41-1.jpeg",
                "/images/kegiatan/41-3.png",
            ],
            startDate: "2024-06-30",
            endDate: "2024-07-04",
            tempat: "online",
            penyelenggara: "UKWU UNESA",
            tingkat: "NAS",
        },
        {
            id: 42,
            name: "STUDIUM GENERALE Empowering Gen Z: Hope or Hurdle? Unleashing Potential to Transform Indonesia",
            description: "Attended a studium generale on Gen Z's role in transforming Indonesia and the potential of young generations facing future challenges.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/42-2.jpeg",
                "/images/kegiatan/42-1.png",
                "/images/kegiatan/42-3.png",
            ],
            startDate: "2024-10-10",
            endDate: "2024-10-10",
            tempat: "UIN Sunan Kalijaga",
            penyelenggara: "HMPS MKS UIN Sunan Kalijaga Yogyakarta",
            tingkat: "NAS",
        },
        {
            id: 43,
            name: "SohiB Competition: Poster with the Theme 'Golden Indonesia: 8 Pillars Towards the Future'",
            description: "Participated in a poster design competition themed on Golden Indonesia and eight pillars of national development towards the future.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/43-2.png",
                "/images/kegiatan/43-1.png",
                "/images/kegiatan/43-3.png",
            ],
            startDate: "2024-10-23",
            endDate: "2024-11-16",
            tempat: "Online",
            penyelenggara: "id_sohib",
            tingkat: "NAS",
        },
        {
            id: 44,
            name: "Frontend vs Backend: A Never-Ending Love-Hate Relationship",
            description: "Attended a seminar on web development dynamics between frontend and backend and collaboration in development teams.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/44-2.png",
                "/images/kegiatan/44-1.jpeg",
                "/images/kegiatan/44-3.png",
            ],
            startDate: "2025-02-06",
            endDate: "2025-02-06",
            tempat: "Online",
            penyelenggara: "indosat ooredoo hutchison",
            tingkat: "REG",
        },
        {
            id: 45,
            name: "I-CHALLENGE 2025 Industry Case Competition",
            description: "Participated in an international industry case competition to solve real business problems with innovative solutions.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/45-2.jpeg",
                "/images/kegiatan/45-1.png",
                "/images/kegiatan/45-3.png",
            ],
            startDate: "2024-12-08",
            endDate: "2025-04-27",
            tempat: "Online",
            penyelenggara: "I-CHALLENGE BRAWIJAYA",
            tingkat: "INT",
        },
        {
            id: 46,
            name: "I-CHALLANGE Business Product and Design Competition",
            description: "Participated in an international business product design competition to develop marketable product innovations.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/46-2.jpeg",
                "/images/kegiatan/46-1.png",
                "/images/kegiatan/46-3.png",
            ],
            startDate: "2024-12-08",
            endDate: "2025-04-27",
            tempat: "Online",
            penyelenggara: "I-CHALLENGE BRAWIJAYA",
            tingkat: "INT",
        },
        {
            id: 47,
            name: "PertaMC: Maintenance Excellence Competition (PERFORMANCE) under the theme 'Asset Integrity Management System (AIMS)'",
            description: "Participated in a maintenance excellence competition themed on asset integrity management systems to understand best practices in industrial maintenance.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/47-2.jpeg",
                "/images/kegiatan/47-1.png",
                "/images/kegiatan/47-3.png",
            ],
            startDate: "2024-12-17",
            endDate: "2025-02-24",
            tempat: "Online",
            penyelenggara: "PertaMC dan Universitas Pertamina",
            tingkat: "INT",
        },
        {
            id: 48,
            name: "I-CHALLANGE Essay Competition",
            description: "Participated in an international essay writing competition to develop academic writing skills and critical thinking.",
            sebagai: "PES", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/48-2.png",
                "/images/kegiatan/48-1.png",
                "/images/kegiatan/48-3.png",
            ],
            startDate: "2024-12-08",
            endDate: "2025-04-27",
            tempat: "Online",
            penyelenggara: "I-CHALLENGE BRAWIJAYA",
            tingkat: "INT",
        },
        {
            id: 49,
            name: "Workshop Series on Career Guidance with the Theme 'Entrepreneurship in Education'",
            description: "Attended a career guidance workshop on entrepreneurship in education to explore edutech business opportunities.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/49-2.jpeg",
                "/images/kegiatan/49-1.png",
                "/images/kegiatan/49-3.png",
            ],
            startDate: "2025-09-23",
            endDate: "2025-09-23",
            tempat: "Cine Club Gedung Ki Ageng Suryamentaram Fakultas Bahasa, Seni dan Budaya (FBSB) Universitas Negeri Yogyakarta (UNY)",
            penyelenggara: "uny",
            tingkat: "UNY",
        },
        {
            id: 50,
            name: "WSBK (Workshop Series Bimbingan Karier) UNY #4",
            description: "Attended a career guidance workshop series to gain guidance in career planning and professional development.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/60-2.png",
                "/images/kegiatan/60-1.jpeg",
                "/images/kegiatan/60-3.png",
            ],
            startDate: "2025-05-17",
            endDate: "2025-05-17",
            tempat: "Ruang Aula Abdullah Sigit FIP UNY lt. 3",
            penyelenggara: "UNY",
            tingkat: "UNY",
        },
        {
            id: 51,
            name: "Campus Hiring: UniTalk with Qiscus",
            description: "Attended a campus recruitment session with Qiscus to learn about the hiring process and career opportunities in the communication technology industry.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/51-2.jpeg",
                "/images/kegiatan/51-1.png",
                "/images/kegiatan/51-3.png",
            ],
            startDate: "2025-09-09",
            endDate: "2025-09-09",
            tempat: "Fakultas Teknik UNY",
            penyelenggara: "UNY dan infinite uny",
            tingkat: "NAS",
        },
        {
            id: 52,
            name: "TechTalk130 by Qiscus, with the topic: 'Inside Context Engineering: Why It Matters and How to Debug Itl'",
            description: "Attended a tech talk on context engineering and debugging techniques to understand best practices in software development.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/52-2.jpeg",
                "/images/kegiatan/52-1.png",
                "/images/kegiatan/52-3.png",
            ],
            startDate: "2025-09-13",
            endDate: "2025-09-13",
            tempat: "BSI KC Sudirman Yogyakarta",
            penyelenggara: "Qiscus",
            tingkat: "NAS",
        },
        {
            id: 53,
            name: "6th Career Guidance Workshop Series (WSBK)",
            description: "Attended the 6th career guidance workshop to gain insights on career preparation and the professional world.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/53-2.jpeg",
                "/images/kegiatan/53-1.png",
                "/images/kegiatan/53-3.png",
            ],
            startDate: "2025-06-29",
            endDate: "2025-06-29",
            tempat: "Ruang Aula Gedung. Magister Doktor Lt. 4, FMIPA UNY",
            penyelenggara: "UNY",
            tingkat: "UNY",
        },
        {
            id: 54,
            name: "Workshop Series on Career Guidance (WSBK) 7th",
            description: "Participated in the 7th career guidance workshop to deepen understanding of professional career development strategies.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/54-2.jpeg",
                "/images/kegiatan/54-1.png",
                "/images/kegiatan/54-3.png",
            ],
            startDate: "2025-07-30",
            endDate: "2025-07-30",
            tempat: "Gedung Layanan Akademik Kampus Kulon Progo",
            penyelenggara: "UNY",
            tingkat: "UNY",
        },
        {
            id: 55,
            name: "IDCamp x Dicoding Live #8 - When Business Questions Meet Machine Learning: A Love Story in Data",
            description: "Attended a live session on applying machine learning to answer business questions and data analysis for decision making.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/55-2.jpeg",
                "/images/kegiatan/55-1.jpeg",
                "/images/kegiatan/55-3.png",
            ],
            startDate: "2025-05-07",
            endDate: "2025-05-07",
            tempat: "online",
            penyelenggara: "dicoding",
            tingkat: "NAS",
        },
        {
            id: 56,
            name: "IDCamp x Dicoding Live #7 – Web3 Engineering for Developers: Skills, Tools, and Career Opportunities",
            description: "Participated in a learning session on Web3 engineering, blockchain technology, and career opportunities in decentralized technology.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/56-2.jpeg",
                "/images/kegiatan/56-1.jpeg",
                "/images/kegiatan/56-3.png",
            ],
            startDate: "2025-04-23",
            endDate: "2025-04-23",
            tempat: "online",
            penyelenggara: "dicoding",
            tingkat: "NAS",
        },
        {
            id: 57,
            name: "elevAIte x Dicoding Live #3 – Data-Driven Future: Master Data Science with the Azure Platform",
            description: "Attended a session on data science using the Azure platform to understand modern tools and practices in cloud data analysis.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/57-2.png",
                "/images/kegiatan/57-1.jpeg",
                "/images/kegiatan/57-3.png",
            ],
            startDate: "2025-03-21",
            endDate: "2025-03-21",
            tempat: "online",
            penyelenggara: "dicoding",
            tingkat: "NAS",
        },
        {
            id: 58,
            name: "IDCamp x Dicoding Live #9 - Unlock Limitless AI Potential with the Agentic Trend",
            description: "Participated in a live session on agentic AI trends and the limitless potential of autonomous AI systems.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/58-2.png",
                "/images/kegiatan/58-1.jpeg",
                "/images/kegiatan/58-3.png",
            ],
            startDate: "2025-06-12",
            endDate: "2025-06-12",
            tempat: "online",
            penyelenggara: "dicoding",
            tingkat: "NAS",
        },
        {
            id: 59,
            name: "WSBK (Workshop Series Bimbingan Karier) UNY #2",
            description: "Attended the 2nd career guidance workshop series to receive guidance on skill development and preparation for entering the professional world.",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/59-2.jpeg",
                "/images/kegiatan/59-1.jpeg",
                "/images/kegiatan/59-3.png",
            ],
            startDate: "2025-03-20",
            endDate: "2025-03-20",
            tempat: "FT UNY",
            penyelenggara: "uny",
            tingkat: "UNY",
        },
        {
            id: 60,
            name: "MCT Summit Indonesia 2025",
            description: "Attended the Microsoft Certified Trainer technology summit to gain current insights on Microsoft technologies and IT education trends.",
            sebagai: "PES", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/50-2.jpeg",
                "/images/kegiatan/50-1.png",
                "/images/kegiatan/50-3.png",
            ],
            startDate: "2025-09-24",
            endDate: "2025-09-25",
            tempat: "Kolektif coworking space & collaboraction, jl. Watugede no.58",
            penyelenggara: "PT. Maribelajar Indonesia Cerdas",
            tingkat: "NAS",
        },
        //terakhir dari presma kegiatan : Workshop Series Bimbingan Karir dengan tema “Entrepreneurship in Education” / Workshop Series on Career Guidance with the Theme 'Entrepreneurship in Education'
        {
            id: 61,
            name: "PRIME: Electronics and Informatics Expo — HIMANIKAFEST",
            description: "PRIME (Electronics and Informatics Expo) is a closing ceremony event for the HIMANIKAFEST committee that features live music performances and celebration activities. This event serves as the grand finale where the winners of the ELINATION competition are announced and awarded. It provides an opportunity for committee members, participants, and attendees to celebrate the success of the entire event series while enjoying entertainment and recognizing outstanding achievements in the electronics and informatics competitions.",
            sebagai: "PAN", 
            jenis: "ORG",
            images: [
                "/images/kegiatan/61-2.jpg",
                "/images/kegiatan/61-1.png",
                "/images/kegiatan/61-3.jpg",
            ],
            startDate: "2024-11-30",
            endDate: "2024-11-30",
            tempat: "Arah Timur Coffee",
            penyelenggara: "HIMANIKA 2024, PRIMEFEST.YK",
            tingkat: "NAS",
        },
        {
            id: 62,
            name: "ELINATION: Electronics and Informatics Competition — Department of Electronics and Informatics Education, Faculty of Engineering, UNY",
            description: "ELINATION is a national-level competition featuring two main categories: UI/UX Design and Line Follower Robot. The UI/UX Design competition challenges participants to create innovative and user-friendly interface designs, while the Line Follower competition tests students' abilities in robotics and electronics by programming robots to autonomously navigate a predetermined path. This event provides a platform for students nationwide to demonstrate their technical skills, creativity, and problem-solving abilities in both digital design and robotics engineering.",
            sebagai: "PAN", 
            jenis: "LOM",
            images: [
                "/images/kegiatan/62-2.jpg",
                "/images/kegiatan/62-1.png",
                "/images/kegiatan/62-3.png",
            ],
            startDate: "2024-10-01",
            endDate: "2024-11-24",
            tempat: "Department of Electronics and Informatics Education, Faculty of Engineering, UNY",
            penyelenggara: "HIMANIKA 2024, PRIMEFEST.YK",
            tingkat: "NAS",
        },
        {
            id: 63,
            name: "National Seminar with the Theme 'AI Implementation in Improving Education Quality through Virtual Reality and Augmented Reality Technologies'",
            description: "This national seminar explores the integration of Artificial Intelligence, Virtual Reality (VR), and Augmented Reality (AR) technologies in educational settings. The event brings together educators, researchers, and technology experts to discuss innovative approaches to enhancing learning experiences through immersive technologies. Participants gain insights into practical AI implementations, VR/AR applications in education, and strategies for improving teaching quality and student engagement through cutting-edge technological solutions.",
            sebagai: "PAN", 
            jenis: "SEM",
            images: [
                "/images/kegiatan/63-2.jpg",
                "/images/kegiatan/63-1.png",
                "/images/kegiatan/63-3.jpg",
            ],
            startDate: "2024-10-02",
            endDate: "2024-10-02",
            tempat: "Gedung KPLT Lantai 3 Fakultas Teknik UNY",
            penyelenggara: "HIMANIKA 2024 dan DPEI FT UNY",
            tingkat: "NAS",
        },
        {
            id: 64,
            name: "SHIBERNIKA — Student Association of Electronics and Informatics",
            description: "SHIBERNIKA is a community-building and bonding event for students in the Electronics and Informatics department. This program focuses on strengthening relationships among students through cultural activities, team-building exercises, and collaborative projects. The event incorporates traditional arts and cultural performances, creating a unique blend of technology education and cultural appreciation while fostering a sense of unity and belonging within the student association.",
            sebagai: "PAN", 
            jenis: "ORG",
            images: [
                "/images/kegiatan/64-2.jpg",
                "/images/kegiatan/64-1.png",
            ],
            startDate: "2024-08-20",
            endDate: "2024-09-28",
            tempat: "Lab. Karawitan FBSB UNY",
            penyelenggara: "HIMANIKA 2024",
            tingkat: "UNY",
        },
        {
            id: 65,
            name: "Campus Orientation Departemen Pendidikan Teknik Elektronika dan Informatika Fakultas Teknik UNY",
            description: "Campus Orientation is a comprehensive introduction program for new students in the Department of Electronics and Informatics Education. This multi-week program familiarizes freshmen with campus facilities, academic requirements, departmental culture, and student life at UNY. Activities include campus tours, meetings with faculty and senior students, introductions to academic resources, and team-building activities designed to help new students transition smoothly into university life and build a strong foundation for their academic journey.",
            sebagai: "PAN", 
            jenis: "ORG",
            images: [
                "/images/kegiatan/65-2.png",
                "/images/kegiatan/65-1.png",
            ],
            startDate: "2024-07-24",
            endDate: "2024-08-09",
            tempat: "Departement of Electronics and Informatics Education, Faculty of Engineering, UNY",
            penyelenggara: "HIMANIKA 2024",
            tingkat: "UNY",
        },
        //tambahan dari kegiatan himanika 2024 yang belum dimasukkan (prime, elination, semnas, shibernika, kampus orientation) kurang (bincang bilokrasi dan studi banding otomotif)
    ];
    
    return NextResponse.json(data);
}