import { NextResponse } from 'next/server';

export async function GET() {
    const sebagai = {
        PES: "Peserta Kegiatan",
        PAN: "Panitia Kegiatan",
    };

    const jenis = {
        LOM: "Lomba",
        ABDI: "Pengabdian Masyarakat",
        SEM: "Seminar",
        PEL: "Pelatihan",
        ORG: "Organisasi",
        CAR: "Karier",
    };

    const tingkat = {
        NAS: "Nasional",
        UNY: "Universitas Negeri Yogyakarta",
    };

    const data = [
        {
            id: 1,
            name: "National Competition for Reasoning 'NALAR. IN' Year 2023",
            description: ".",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/1-1.png",
                "/images/kegiatan/1-2.png",
            ],
            startDate: "2023-03-13",
            endDate: "2023-03-13",
            tempat: "Universitas Negeri Yogyakarta",
            penyelenggara: "Universitas Negeri Yogyakarta",
            tingkat: "NAS",
        },
        {
            id: 2,
            name: "National Level Indonesian Performing Arts Festival (FSPI) 2023",
            description: ".",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/2-2.jpeg",
                "/images/kegiatan/2-1.jpg",
            ],
            startDate: "2023-03-01",
            endDate: "2023-04-28",
            tempat: "UNIVERSITAS NEGERI YOGYAKARTA",
            penyelenggara: "FSPI UNIVERSITAS NEGERI YOGYAKARTA",
            tingkat: "NAS",
        },
        {
            id: 3,
            name: "Community Service",
            description: ".",
            sebagai: "PAN",
            jenis: "ABDI",
            images: [
                "/images/kegiatan/3-2.jpeg",
                "/images/kegiatan/3-1.jpg",
            ],
            startDate: "2023-09-16",
            endDate: "2023-09-17",
            tempat: "Dusun Batanggede, Kelurahan Tambak Rejo, Tempel, Sleman, Yogyakarta",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 4,
            name: "Humanitarian Project",
            description: ".",
            sebagai: "PAN",
            jenis: "ABDI",
            images: [
                "/images/kegiatan/4-2.jpeg",
                "/images/kegiatan/4-1.png",
            ],
            startDate: "2023-09-02",
            endDate: "2023-09-02",
            tempat: "Panti Asuhan Al - Hikmah Sejalan, Wukirsari, Cangkringan, Plosokarep, Umbulharjo, Selman, DI Yogyakarta",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 5,
            name: "Industrial Visit",
            description: ".",
            sebagai: "PAN",
            jenis: "CAR",
            images: [
                "/images/kegiatan/5-2.jpeg",
                "/images/kegiatan/5-1.png",
            ],
            startDate: "2023-09-04",
            endDate: "2023-09-07",
            tempat: "Jakarta - Bandung",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 6,
            name: "ARTOCIUS Poster & Short Movie NATIONAL COMPETITION 2023",
            description: ".",
            sebagai: "PES",
            jenis: "LOM",
            images: [
                "/images/kegiatan/6-2.jpeg",
                "/images/kegiatan/6-1.jpg",
            ],
            startDate: "2023-07-22",
            endDate: "2023-07-31",
            tempat: "online",
            penyelenggara: "Himpunan Mahasiswa Pendidikan IPS Bidang Media dan Jaringan",
            tingkat: "NAS",
        },
        {
            id: 7,
            name: "National Seminar on Electronics and Information Engineering Education (SNPTEI) 2023",
            description: ".",
            sebagai: "PAN",
            jenis: "SEM",
            images: [
                "/images/kegiatan/7-2.jpeg",
                "/images/kegiatan/7-1.png",
            ],
            startDate: "2023-09-26",
            endDate: "2023-09-26",
            tempat: "Fakultas Teknik UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 8,
            name: "Seminar Nasional Matematika Ke-15 Universitas Gadjah Mada 'The Future of Criptography and Cybersecurity in Industrial Application'",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/8-2.jpeg",
                "/images/kegiatan/8-1.jpeg",
                "/images/kegiatan/8-3.png",
            ],
            startDate: "2023-09-24",
            endDate: "2023-09-24",
            tempat: "FMIPA UGM",
            penyelenggara: "Himatika UGM",
            tingkat: "NAS",
        },
        {
            id: 9,
            name: "National Seminar with the theme 'Economic Literacy and Business in the 5.0 Era'",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/9-2.jpeg",
                "/images/kegiatan/9-1.jpeg",
                "/images/kegiatan/9-3.png",
            ],
            startDate: "2023-05-27",
            endDate: "2023-05-27",
            tempat: "FEB UNY",
            penyelenggara: "HMPE FEB UNY",
            tingkat: "NAS",
        },
        {
            id: 10,
            name: "Digital Economy Academy",
            description: ".",
            sebagai: "PES",
            jenis: "PEL",
            images: [
                "/images/kegiatan/10-2.jpeg",
                "/images/kegiatan/10-1.jpeg",
                "/images/kegiatan/10-3.png",
            ],
            startDate: "2023-06-24",
            endDate: "2023-06-24",
            tempat: "Ruang Ki Hadjar Dewantara, Fakultas Ilmu Sosial, Hukum dan Ilmu Politik Universitas Negeri Yogyakarta",
            penyelenggara: "BEM KM UNY",
            tingkat: "NAS",
        },
        {
            id: 11,
            name: "Seminar Brave Public Speaking 'Unlock Your Voice, Take Your Chance'",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/11-2.jpeg",
                "/images/kegiatan/11-1.jpeg",
                "/images/kegiatan/11-3.png",
            ],
            startDate: "2024-04-27",
            endDate: "2024-04-27",
            tempat: "Aula Lantai 3 Gedung Student Center UNY",
            penyelenggara: "FOMUNY 2024",
            tingkat: "UNY",
        },
        {
            id: 12,
            name: "Seminar Brave Public Speaking with Fomuny 'Be A Good Speaker for The Better Future''",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/12-2.jpeg",
                "/images/kegiatan/12-1.jpeg",
                "/images/kegiatan/12-3.png",
            ],
            startDate: "2023-03-04",
            endDate: "2023-03-04",
            tempat: "Zoom Meeting / Aula Lantai 3 Gedung Student Center UNY",
            penyelenggara: "FOMUNY 2023",
            tingkat: "UNY",
        },
        {
            id: 13,
            name: "Smart Way For TOEFL FOMUNY 2023 'Do your best and reach your achievement with TOEFL'",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/13-1.jpeg",
                "/images/kegiatan/13-2.png",
            ],
            startDate: "2023-09-02",
            endDate: "2023-09-02",
            tempat: "Zoom Meeting / Gedung KPLT Lantai 2 FT UNY",
            penyelenggara: "FOMUNY 2023",
            tingkat: "UNY",
        },
        {
            id: 14,
            name: "Media School 'Become a Logo Design Expert in the industrial Field of the Modern Era'",
            description: ".",
            sebagai: "PES",
            jenis: "PEL",
            images: [
                "/images/kegiatan/14-2.jpeg",
                "/images/kegiatan/14-1.jpeg",
                "/images/kegiatan/14-3.png",
            ],
            startDate: "2024-05-19",
            endDate: "2024-05-19",
            tempat: "FISHIPOL UNY",
            penyelenggara: "HIMA PKnH 2024",
            tingkat: "UNY",
        },
        {
            id: 15,
            name: "Campus Orientation DPTEI UNY 2023",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/15-2.jpeg",
                "/images/kegiatan/15-1.png",
            ],
            startDate: "2023-08-11",
            endDate: "2023-08-11",
            tempat: "DPTEI FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 16,
            name: "SHIBERNIKA Leadership Training 2023",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/16-2.jpeg",
                "/images/kegiatan/16-1.png",
            ],
            startDate: "2023-09-30",
            endDate: "2023-10-01",
            tempat: "Desa Wisata Tinalah",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 17,
            name: "PI and Student Internship Debriefing Information",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/17-2.jpeg",
                "/images/kegiatan/17-1.jpeg",
                "/images/kegiatan/17-3.png",
            ],
            startDate: "2024-03-27",
            endDate: "2024-03-28",
            tempat: "Aula KPLT Lt.3 FT UNY",
            penyelenggara: "FT UNY",
            tingkat: "UNY",
        },
        {
            id: 18,
            name: "Upgrading HIMANIKA Management 2023",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/18-2.jpeg",
                "/images/kegiatan/18-1.png",
            ],
            startDate: "2023-05-20",
            endDate: "2023-05-21",
            tempat: "Villa Pondok Omah Kayu",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 19,
            name: "HIMANIKA Humanitarian Project 2024",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/19-2.jpeg",
                "/images/kegiatan/19-1.png",
            ],
            startDate: "2024-05-05",
            endDate: "2024-05-05",
            tempat: "Jl. Pajangan, KalakIjo, Guwosari, Kec. Pajangan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55751",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 20,
            name: "HIMANIKA Community Service 2024",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/20-2.jpeg",
                "/images/kegiatan/20-1.png",
            ],
            startDate: "2024-05-04",
            endDate: "2024-05-05",
            tempat: "Jl. Pajangan, KalakIjo, Guwosari, Kec. Pajangan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55751",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 21,
            name: "UPGRADING HIMANIKA 2024",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/21-2.jpeg",
                "/images/kegiatan/21-1.png",
            ],
            startDate: "2024-05-11",
            endDate: "2024-05-12",
            tempat: "Jl. Sedayu-Gesikan, Gesikan I, Wijirejo, Kec. Pandak, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55761",
            penyelenggara: "HIMANIKA FT UNY 2024",
            tingkat: "UNY",
        },
        {
            id: 22,
            name: "Comparative Study of KMTEDI SV UGM X HIMANIKA FT UNY",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/22-2.jpeg",
                "/images/kegiatan/22-1.png",
                "/images/kegiatan/22-3.png",
            ],
            startDate: "2023-09-24",
            endDate: "2023-09-24",
            tempat: "Hall Perpustakaan SV UGM",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "NAS",
        },
        {
            id: 23,
            name: "HME FT UNY X HIMANIKA FT UNY Visit Reception",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/23-2.jpeg",
                "/images/kegiatan/23-1.png",
                "/images/kegiatan/23-3.png",
            ],
            startDate: "2023-06-17",
            endDate: "2023-06-17",
            tempat: "Ruang Teater FT UNY",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 24,
            name: "Comparative Study of HIMANIKA FT UNY X HIMAKI UNY",
            description: ".",
            sebagai: "PAN",
            jenis: "ORG",
            images: [
                "/images/kegiatan/24-2.jpeg",
                "/images/kegiatan/24-1.png",
                "/images/kegiatan/24-3.png",
            ],
            startDate: "2023-04-02",
            endDate: "2023-04-02",
            tempat: "Ruang Seminar FMIPA",
            penyelenggara: "HIMANIKA FT UNY",
            tingkat: "UNY",
        },
        {
            id: 25,
            name: "ENTREPRENEURSHIP DISCUSSION 'Mastering Content Marketing: Rahasia Sukses Tingkatkan Penjualan Lewat Konten Kreatif di 3 Platform Sekaligus (Reels, TikTok,&Short)'",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/25-2.jpeg",
                "/images/kegiatan/25-1.jpeg",
                "/images/kegiatan/25-3.png",
            ],
            startDate: "2023-09-17",
            endDate: "2023-09-17",
            tempat: "ABDULLAH SIGIT HALL LANTAI 3",
            penyelenggara: "BEM FIPP UNY",
            tingkat: "UNY",
        },
        {
            id: 26,
            name: "KOSAN#3 National Insight Towards the 2024 Elections",
            description: ".",
            sebagai: "PES",
            jenis: "SEM",
            images: [
                "/images/kegiatan/26-2.jpeg",
                "/images/kegiatan/26-1.png",
                "/images/kegiatan/26-3.png",
            ],
            startDate: "2023-05-04",
            endDate: "2023-05-04",
            tempat: "Takom 1922 Cafe & Resto Yogyakarta",
            penyelenggara: "Garda Institute",
            tingkat: "NAS",
        },
    ];

    return NextResponse.json(data);
}