import { NextResponse } from 'next/server';

export async function GET() {
    const gelar = {
        SAT: "Juara 1",
        DUA: "Juara 2",
        TIG: "Juara 3",
        FIN: "Finalis",
        PES: "Peserta Kejuaraan",
    };

    const kategori = {
        OLI: "Olimpiade",
        KOM: "Kompetisi",
    };

    const negara = {
        IND: "Indonesia",
    };

    const tingkat = {
        NAS: "Nasional",
        INT: "Internasional",
    };

    const bidang = {
        PEN: "Penalaran",
    };

    const sebagai = {
        SOL: "Individu",
        SQU: "Kelompok",
    };

    const data = [
        {
            id: 1,
            gelar: "SAT",
            nama: "LDC (Language Day Competition) English Language Field",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "POSI (Pusat Olimpiade Sains Indonesia)",
            jumlah_negara: 1,
            Jumlah_institusi: 74,
            jumlah_peserta: 3565,
            startDate: "2024-05-12",
            endDate: "2024-05-12",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "LDC 2024 – Language Day Competition 2024 with the theme “Passion for Science” is open to university students, teachers, and students at the Elementary (SD/MI), Junior High (SMP/MTs), and Senior High/Vocational School levels (SMA/MA/SMK), featuring competitions in Indonesian, Arabic, and English languages.",
            images: [
                "/images/juara/1-1.jpg",
                "/images/juara/1-2.png",
                "/images/juara/1-3.png",
            ],
        },
        {
            id: 2,
            gelar: "SAT",
            nama: "KSNHP (National Science Competition Education Day) Mathematics",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "BRAINDICATOR",
            jumlah_negara: 1,
            Jumlah_institusi: 50,
            jumlah_peserta: 1000,
            startDate: "2024-05-12",
            endDate: "2024-05-12",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "The National Science Competition for Education Day (KSN HP) 2024 is a national-level science competition for elementary, junior high, and senior high school students (SD/MI, SMP/MTs, SMA/MA), university students, and teachers. The competition will be held online on May 12, 2024. Participants can compete in various subjects such as Mathematics, Science, Indonesian Language, and many others.",
            images: [
                "/images/juara/2-1.jpg",
                "/images/juara/2-2.png",
                "/images/juara/2-3.png",
            ],
        },
        {
            id: 3,
            gelar: "SAT",
            nama: "Future Scientist Olympiad (FUSO 2024) in Physics",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "POSI (Pusat Olimpiade Sains Indonesia)",
            jumlah_negara: 1,
            Jumlah_institusi: 50,
            jumlah_peserta: 7596,
            startDate: "2024-05-19",
            endDate: "2024-05-19",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "The Future Scientist Olympiad, organized by FUSO in 2024, is a prestigious academic competition aimed at fostering interest in science among students and teachers across various educational levels. This esteemed event invites students from Elementary School (SD/MI), Junior High School (SMP/MTs), and Senior/Vocational High School (SMA/MA/SMK), along with their teachers, to participate in various subjects such as Mathematics, Science, English, Economics, History, Geography, and Indonesian Language. Participants have the opportunity to showcase their knowledge and skills through a series of online assessment rounds leading up to the final round on May 21, 2024. This olympiad serves as a platform for intellectual development, enhancing critical thinking, problem-solving abilities, and fostering a deeper appreciation for scientific inquiry among the nation’s bright young generation.",
            images: [
                "/images/juara/3-1.jpg",
                "/images/juara/3-2.png",
                "/images/juara/3-3.png",
            ],
        },
        {
            id: 4,
            gelar: "SAT",
            nama: "National Education Science Olympiad (OSH) 2024 in Chemistry",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "Pusat Kejuaraan Sains Nasional (PUSKANAS)",
            jumlah_negara: 1,
            Jumlah_institusi: 50,
            jumlah_peserta: 7596,
            startDate: "2024-05-26",
            endDate: "2024-05-26",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "The National Education Day Science Olympiad (OSH) is a prestigious national-level competition organized for students and university students across various educational levels, ranging from elementary and junior high school to senior high/vocational school and higher education. This competition provides a platform for participants to showcase their academic abilities in a wide range of subjects, including Mathematics, Civic Education, Science, Languages, Geography, Economics, Biology, Chemistry, History, Medicine, Astronomy, Information and Technology, and Physics.The olympiad offers attractive rewards such as laptops, educational scholarships, medals, certificates, and access to Higher Order Thinking Skills (HOTS) questions. By participating in OSH, students and university students can sharpen their critical thinking skills, foster healthy competitive spirit, and gain recognition for their academic achievements.",
            images: [
                "/images/juara/4-1.jpg",
                "/images/juara/4-2.png",
                "/images/juara/4-3.png",
            ],
        },
        {
            id: 5,
            gelar: "SAT",
            nama: "National Education Science Olympiad (OSH) 2024 English",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "Pusat Kejuaraan Sains Nasional (PUSKANAS)",
            jumlah_negara: 1,
            Jumlah_institusi: 50,
            jumlah_peserta: 7596,
            startDate: "2024-05-26",
            endDate: "2024-05-26",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "The National Education Day Science Olympiad (OSH) is a prestigious national-level competition organized for students and university students across various educational levels, ranging from elementary and junior high school to senior/vocational high school and higher education. This competition serves as a platform for participants to showcase their academic abilities in various fields such as Mathematics, Civics, Science, Languages, Geography, Economics, Biology, Chemistry, History, Medicine, Astronomy, Information and Technology, and Physics. The olympiad offers attractive rewards such as laptops, educational scholarships, medals, certificates, and access to Higher Order Thinking Skills (HOTS) questions. By participating in OSH, students and university students can sharpen their critical thinking skills, foster a healthy competitive spirit, and gain recognition for their academic achievements.",
            images: [
                "/images/juara/5-1.jpg",
                "/images/juara/5-2.png",
                "/images/juara/5-3.png",
            ],
        },
        {
            id: 6,
            gelar: "DUA",
            nama: "PISA (Posi Science Assessment) Biology",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "POSI (Pusat Olimpiade Sains Indonesia)",
            jumlah_negara: 1,
            Jumlah_institusi: 45,
            jumlah_peserta: 6172,
            startDate: "2024-06-04",
            endDate: "2024-06-04",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "PISA (POSI Science Assessment) 2024 is a science assessment event for university students, teachers, and students at the elementary (SD/MI), junior high (SMP/MTs), and senior/vocational high school levels (SMA/MA/SMK), organized by POSI (the Indonesian Science Olympiad Association). The competition covers several subjects, including Mathematics, Physics, Chemistry, Biology, Economics, English, Civics (PPKN), and Indonesian Language. The registration period runs from April 18 to May 31, 2024, with the administrative selection announcement on June 2, 2024, followed by the final results on June 3, 2024. Participants will receive an award certificate, a certificate granting access to problem explanations, and opportunities to connect with peers from across Indonesia. Registration is free and conducted online through the link provided in the poster.",
            images: [
                "/images/juara/6-1.jpg",
                "/images/juara/6-2.png",
                "/images/juara/6-3.png",
            ],
        },
        {
            id: 7,
            gelar: "SAT",
            nama: "Student Science Olympiad (OSM) 2024 Computer Field",
            kategori: "OLI",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "POSI (Pusat Olimpiade Sains Indonesia)",
            jumlah_negara: 1,
            Jumlah_institusi: 30,
            jumlah_peserta: 450,
            startDate: "2024-06-15",
            endDate: "2024-06-15",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SOL",
            deskripsi: "Participating in the 2024 Student Science Olympiad, a national-level competition organized by POSI (Pekan Olimpiade Sains Indonesia). This olympiad covers various fields of study, including Mathematics, Physics, Biology, Chemistry, Economics, Geography, Astronomy, English, Earth Science, and Computer Science. The competition is conducted online on June 15, 2024, involving university students from across Indonesia. This event provides an opportunity to assess academic abilities, gain recognition through certificates and awards, and build connections with talented students from all over the country.",
            images: [
                "/images/juara/7-1.jpg",
                "/images/juara/7-2.png",
                "/images/juara/7-3.png",
            ],
        },
        {
            id: 8,
            gelar: "FIN",
            nama: "HMJ Perbankan Syariah INTERNATIONAL CALL FOR PAPER COMPETITION 2024",
            kategori: "KOM",
            tempat: "Dilaksanakan Secara Daring Internasional",
            negara: "IND",
            penyelenggara: "Perbankan Syariah UINSI Samarinda",
            jumlah_negara: 5,
            Jumlah_institusi: 16,
            jumlah_peserta: 30,
            startDate: "2024-10-28",
            endDate: "2024-12-21",
            tingkat: "INT",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "The International Call for Papers Competition 2024, themed “The Future of Islamic Banking: The Role of the Young Generation in Driving Sustainability in the Digital Revolution Era,” invites participants to explore how the younger generation can contribute to advancing sustainable practices within the rapidly evolving digital landscape of Islamic banking.",
            images: [
                "/images/juara/8-1.png",
                "/images/juara/8-2.png",
                "/images/juara/8-3.png",
            ],
        },
        {
            id: 9,
            gelar: "FIN",
            nama: "NATIONAL BUSINESS PLAN COMPETITION Sharia Finance Expo 9th 2024",
            kategori: "KOM",
            tempat: "UIN SUNAN KALIJAGA YOGYAKARTA",
            negara: "IND",
            penyelenggara: "UIN SUNAN KALIJAGA YOGYAKARTA",
            jumlah_negara: 1,
            Jumlah_institusi: 50,
            jumlah_peserta: 210,
            startDate: "2024-09-15",
            endDate: "2024-10-19",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "The National Business Plan Competition: SFE Olympic 9 is a national-level business plan competition held as part of the Sharia Finance Expo 9, providing a platform for participants to develop and present innovative business ideas within the sharia finance ecosystem.",
            images: [
                "/images/juara/9-1.png",
                "/images/juara/9-2.png",
                "/images/juara/9-3.png",
            ],
        },
        {
            id: 10,
            gelar: "PES",
            nama: "KRNH Competition 2025 Mosque Plan Competition",
            kategori: "KOM",
            tempat: "Universitas Sebelas Maret",
            negara: "IND",
            penyelenggara: "Universitas Sebelas Maret",
            jumlah_negara: 1,
            Jumlah_institusi: 35,
            jumlah_peserta: 185,
            startDate: "2025-02-02",
            endDate: "2025-03-15",
            tingkat: "NAS",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "Mosque Plan Competition. In the KRNH Competition 2025 with the theme “Moments of Ramadan: Harmony of Ramadan in the Frame of the Archipelago,” held from February 2 to March 15, 2025, by Nurul Huda Mosque, Sebelas Maret University, Surakarta.",
            images: [
                "/images/juara/10-1.png",
                "/images/juara/10-2.jpg",
                "/images/juara/10-3.png",
            ],
        },
        {
            id: 11,
            gelar: "PES",
            nama: "Internasional CHALLENGE 2025 Business Product and Design Competition",
            kategori: "KOM",
            tempat: "Universitas Brawijaya",
            negara: "IND",
            penyelenggara: "Universitas Brawijaya",
            jumlah_negara: 10,
            Jumlah_institusi: 100,
            jumlah_peserta: 100,
            startDate: "2024-12-08",
            endDate: "2025-04-27",
            tingkat: "INT",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "I-CHALLENGE 2025 is a big event that encourages the international scope of universities to unleash their innovative ideas in creating a comprehensive solution for future sustainability, It consists 3 main competitions: Essay Competition (EC), Business Product and Design Competition (BPDC), Industry Case Competition (ICAC)",
            images: [
                "/images/juara/11-1.png",
                "/images/juara/11-2.jpg",
                "/images/juara/11-3.png",
            ],
        },
        {
            id: 12,
            gelar: "PES",
            nama: "Lomba Internasional CHALLENGE 2025 Essay Competition",
            kategori: "KOM",
            tempat: "Universitas Brawijaya",
            negara: "IND",
            penyelenggara: "Universitas Brawijaya",
            jumlah_negara: 10,
            Jumlah_institusi: 100,
            jumlah_peserta: 100,
            startDate: "2024-12-08",
            endDate: "2025-04-27",
            tingkat: "INT",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "I-CHALLENGE 2025 is a big event that encourages the international scope of universities to unleash their innovative ideas in creating a comprehensive solution for future sustainability, It consists 3 main competitions: Essay Competition (EC), Business Product and Design Competition (BPDC), Industry Case Competition (ICAC)",
            images: [
                "/images/juara/12-1.png",
                "/images/juara/12-2.jpg",
                "/images/juara/12-3.png",
            ],
        },
        {
            id: 13,
            gelar: "PES",
            nama: "PetaMC for Maintenance Excellence Competition (PERFORMANCE), Scientific Writing Category",
            kategori: "KOM",
            tempat: "Online",
            negara: "IND",
            penyelenggara: "PertaMC dan Universitas Pertamina",
            jumlah_negara: 5,
            Jumlah_institusi: 50,
            jumlah_peserta: 200,
            startDate: "2024-12-17",
            endDate: "2025-02-24",
            tingkat: "INT",
            bidang: "PEN",
            sebagai: "SQU",
            deskripsi: "PERFORMANCE (PertaMC for Maintenance Excellence Competition) – Scientific Writing Category The PERFORMANCE Scientific Writing Competition is a national-level contest organized by PT Pertamina Maintenance and Construction (PertaMC) in collaboration with Universitas Pertamina. This competition invites university students across Indonesia to develop innovative, research-based ideas that support the implementation of the Asset Integrity Management System (AIMS) in the oil and gas industry. Participants are challenged to propose solutions that enhance maintenance efficiency, safety, and sustainability in line with Pertamina’s future energy goals.",
            images: [
                "/images/juara/13-1.png",
                "/images/juara/13-2.jpeg",
                "/images/juara/13-3.png",
            ],
        },
        //terakhir dari presma prestasi : Lomba Karya Tulis Ilmiah Lomba PetaMC for Maintenance Excellence Competition (PERFORMANCE), Cabang Lomba Karya Tulis Ilmiah / PetaMC for Maintenance Excellence Competition (PERFORMANCE), Scientific Writing Category
    ];
    
    return NextResponse.json(data);
}